# this is mysql config
[list]
    [list.default]
        driver_name = "mysql"
        data_source_name = "root:123.com@tcp(10.2.40.42:3307)/test?charset=utf8&parseTime=true&loc=Asia%2FChongqing"
        max_open_conn = 20
        max_idle_conn = 10
        max_conn_life_time = 100